[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

[profile.ci]
fuzz_runs = 1000
verbosity = 4

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
flare = "${FLARE_RPC_URL}"
songbird = "${SONGBIRD_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
flare = { key = "${FLARESCAN_API_KEY}" }


